[package]
name = "pods"
version = "1.0.7"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.2", package = "libadwaita", features = ["v1_2"] }
anyhow = "1"
ashpd = { version = "0.4.0-alpha.2", default-features = false, features = ["gtk4", "tokio"] }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.5", package = "gtk4", features = ["gnome_43"] }
indexmap = { version = "1", features = ["serde"] }
log = "0.4"
names = { version = "0.14", default-features = false }
once_cell = "1"
panel = { version = "0.1", package = "libpanel" }
paste = "1"
podman-api = { git = "https://github.com/vv9k/podman-api-rs.git", default-features = false }
serde = "1"
serde_json = "1"
sourceview5 = "0.5"
syslog = "6"
tokio = { version = "1", features = ["fs", "io-util", "process", "rt-multi-thread", "sync"] }
tokio-tar = "0.3"
vte = { version = "0.11", default-features = false }
vte4 = "0.5"

[profile.release]
lto = true
